export const GET_HOME_COMMON_DATA = "GET_HOME_COMMON_DATA";
export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const GET_FEATURED_PRODUCT_DATA = "GET_FEATURED_PRODUCT_DATA";
export const GET_DOWNLOAD_PRODUCT_DATA = "GET_DOWNLOAD_PRODUCT_DATA";
export const GET_FEVORITE_PRODUCT_DATA = "GET_FEVORITE_PRODUCT_DATA";
export const GET_WHY_US_DATA = "GET_WHY_US_DATA";
export const GET_TESTMONIAL_DATA = "GET_TESTMONIAL_DATA";
export const GET_BLOGS_DATA = "GET_BLOGS_DATA"